### ISSUE TITLE
GraphQL Handler CustomFetch Headers Undefined

### ISSUE THREAD

**Issue by jed-i** [the-guild-org/Stack#17]
When using the customFetch for GraphQL handler the headers are undefined resulting in error. The same setup is working for OpenAPI handler.

Steps to reproduce

.meshrc.yaml

```
sources:
  - name: MyGraphQLApi
    handler:
      graphql:
        endpoint: https://test/graphql
        customFetch: ./src/customFetch.js
```

cusotmFetch.js

`module.exports = async function(url, args, context) {}`

Result

`Cannot read property 'headers' of undefined`

Stack

```

TypeError: Cannot read property 'headers' of undefined
    at /node_modules/@graphql-tools/url-loader/index.js:451:49

Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.
🕸️: { name: "Error", stack: "Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.\n    at Object.getMesh (/node_modules/@graphql-mesh/runtime/index.js:112:15)\n    at async module.exports (/server.js:4:22)\n    at async Object.handler (/node_modules/@graphql-mesh/cli/bin.js:793:17)", message: "Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output." }
```
